

name: Java CI with Maven
on:
  
  push:
    branches: [main]



jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Build with Maven
        run: mvn clean test
        
      - name: Send email
        uses: AlexisMateo/sendmail-action@5
        with:
         smtp-server: ${{ secrets.SMTP_SERVER }}
         smtp-server-port: ${{ secrets.SMTP_SERVER_PORT }}
         auth-user: ${{ secrets.AUTH_USER }}
         auth-password: ${{secrets.EMAIL_PASSWORD }}
         subject: correciones a ${{github.repository}}
         body: Build job of ${{github.repository}} completed successfully!
   
       
         from: ${{ secrets.EMAIL_FROM }}
         to: ${{ secrets.EMAIL_RECIVER }}
         is-tls: false
         commit-message: true
  

